### ISSUE TITLE
Add Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by milanm** [milanm/Cloud-Product-Mapping#5]
If anyone wants to contribute, feel free to open the PR and I will update the image.

**Comment by dralquinta** [comment]
@milanm do you have the template to add OCI stuff in here? Main branch doesn't contain anything apart from png and pdf file.

**Comment by milanm** [comment]
No, you can just prepare a PR with all additions for OCI (text and links in every category) and send me the icons and I will add it to the image.

**Comment by milanm** [comment]
It is just added.
